export enum CustomActions {
  POST_ACTION_COMPLETED = "POST_ACTION_COMPLETED",
  EDIT_ACTION_COMPLETED = "EDIT_ACTION_COMPLETED",
  CHATROOM_LEAVE_ACTION_COMPLETED = "CHATROOM_LEAVE_ACTION_COMPLETED",
}
