export enum CustomActions {
  POST_ACTION_COMPLETED = "POST_ACTION_COMPLETED",
  EDIT_ACTION_COMPLETED = "EDIT_ACTION_COMPLETED",
  CHATROOM_LEAVE_ACTION_COMPLETED = "CHATROOM_LEAVE_ACTION_COMPLETED",
  UPDATE_LAST_CONVERSATION_ON_CHANNEL_TILES = "UPDATE_LAST_CONVERSATION_ON_CHANNEL_TILES",
}
