export enum ReplyDmQueries {
  GROUP_CHANNEL = "group_channel",
  DM_CHANNEL = "dm_feed_v2",
  REPLY_PRIVATELY_ALLOWED_TO_ALL_MEMBERS = "1",
  REPLY_PRIVATELY_ALLOWED_TO_COMMUNITY_MANAGERS = "2",
  REPLY_PRIVATELY_NOT_ALLOWED = "0",
}
