import { OgTag } from "./getOgTagResponse";

/* eslint-disable @typescript-eslint/no-explicit-any */
export interface GetSyncConversationsResponse {
  success: boolean;
  data: {
    chatroom_meta: {
      [key: string]: {
        about: string;
        access: any;
        access_without_subscription: boolean;
        attachment_count: number;
        attachments_uploaded: boolean;
        attending_status: boolean;
        auto_follow_done: boolean;
        card_id: number;
        chat_request_created_at: any;
        chat_request_state: any;
        chat_requested_by_id: any;
        chatroom_image_url: string;
        chatroom_with_user_id: any;
        co_hosts: string;
        community_id: number;
        created_at: number;
        custom_tag: string;
        date: string;
        date_epoch: number;
        date_time: number;
        deleted_by_user_id: any;
        device_id: string;
        event_kind: string;
        expiry_time: any;
        external_seen: boolean;
        follow_status: boolean;
        has_been_named: boolean;
        has_files: boolean;
        has_reactions: boolean;
        header: string;
        id: number;
        internal_link: any;
        is_edited: boolean;
        is_paid: boolean;
        is_pending: boolean;
        is_private: boolean;
        is_private_member: boolean;
        is_secret: boolean;
        is_tagged: boolean;
        last_seen_conversation_id: number;
        member_can_message: boolean;
        mute_status: boolean;
        og_tags: any;
        online_link: string;
        online_link_type: any;
        secret_chatroom_left: boolean;
        secret_chatroom_participants: any;
        share_link: string;
        state: number;
        title: string;
        topic_id: any;
        type: number;
        updated_at: number;
        user_id: number;
      };
    };
    chatroom_reactions_meta: any;
    community_meta: {
      [key: string]: {
        id: number;
        image_url: string;
        is_paid: boolean;
        name: string;
        purpose: string;
        sub_type: number;
        type: number;
      };
    };
    conv_attachments_meta: any;
    conv_polls_meta: Record<string, PollMeta[]>;
    conv_reactions_meta: {
      [key: string]: Array<{
        chatroom_id: number;
        conversation_id: number;
        id: number;
        reaction: string;
        user_id: number;
      }>;
    };
    conversations_data: Array<{
      reply_conversation_object: any;
      allow_add_option: boolean;
      answer: string;
      api_version: number;
      attachment_count: number;
      attachments_uploaded: boolean;
      card_id: number;
      co_hosts: any;
      community_id: number;
      created_at: string;
      created_epoch: number;
      date: string;
      deleted_by_user_id: number | string | any;
      device_id: string;
      end_time: number;
      expiry_time: number | any;
      has_files: boolean;
      has_reactions: boolean;
      header: string | any;
      id: number;
      internal_link: any;
      is_anonymous: boolean;
      is_edited: boolean;
      last_updated: number;
      location: any;
      location_lat: any;
      location_long: any;
      multiple_select_no: number | any;
      multiple_select_state: number | any;
      og_tags: OgTag;
      online_link_enable_before: number;
      poll_answer_text: string;
      poll_type: number;
      poll_type_text: string;
      preview_chatroom_id: number | any;
      preview_community_id: number | any;
      preview_type: string;
      reply_chatroom_id: number | any;
      reply_id: number | any;
      start_time: number;
      state: number;
      submit_type_text: string | any;
      temporary_id: number | string | any;
      to_show_results: boolean;
      user_id: number;
      widget_id: string;
    }>;
    user_meta: {
      [key: string]: {
        created_at: number;
        custom_title: string;
        id: number;
        image_link: string;
        image_url: string | any;
        is_guest: boolean;
        is_owner: boolean;
        name: string;
        sdk_client_info: {
          community_id: number;
          id: number;
          user: number;
          user_unique_id: string;
          uuid: string;
          widget_id: string;
        };
        state: number;
        user_unique_id: string;
        uuid: string;
      };
    };
    conversation_meta: Record<number | string, ConversationMetaObject>;
    widgets: Record<string, any>;
  };
}
interface ConversationMetaObject {
  allow_add_option: boolean;
  answer: string;
  api_version: number;
  attachment_count: number;
  attachments_uploaded: boolean;
  card_id: number;
  co_hosts: any;
  community_id: number;
  created_at: string;
  created_epoch: number;
  date: string;
  deleted_by_user_id: number | any;
  device_id: string;
  end_time: number;
  expiry_time: number | any;
  has_files: boolean;
  has_reactions: boolean;
  header: string | any;
  id: number;
  internal_link: any;
  is_anonymous: boolean;
  is_edited: boolean;
  last_updated: number;
  location: any;
  location_lat: any;
  location_long: any;
  multiple_select_no: number | any;
  multiple_select_state: number | any;
  og_tags: OgTag | any;
  online_link_enable_before: number;
  poll_answer_text: string;
  poll_type: number | any;
  poll_type_text: any;
  preview_chatroom_id: any;
  preview_community_id: any;
  preview_type: string;
  reply_chatroom_id: number | any;
  reply_id: number | any;
  start_time: number;
  state: number;
  submit_type_text: string | any;
  temporary_id: number | any;
  to_show_results: boolean;
  user_id: number;
  widget_id: string;
}
interface PollMeta {
  conversation_id: number;
  count: any | number;
  id: number;
  is_selected: boolean;
  no_votes: number;
  percentage: any | number;
  text: string;
  user_id: number;
}
